interface FixFeaturesAttributes {
  FeatureType: string;
  Name: string;
  Description?: string;
  Quote?: string;
  Coast?: boolean;
  NoCoast?: boolean;
  NoRiver?: boolean;
  NoAdjacentFeatures?: boolean;
  RequiresRiver?: boolean;
  MovementChange?: number;
  SightThroughModifier?: number;
  Impassable?: boolean;
  NaturalWonder?: boolean;
  RemoveTech?: string;
  Removable?: boolean;
  AddCivic?: string;
  DefenseModifier?: number;
  AddsFreshWater?: boolean;
  Appeal?: number;
  MinDistanceLand?: number;
  MaxDistanceLand?: number;
  NotNearFeature?: boolean;
  Lake?: boolean;
  Tiles?: number;
  Adjacent?: boolean;
  NoResource?: boolean;
  DoubleAdjacentTerrainYield?: boolean;
  NotCliff?: boolean;
  MinDistanceNW?: number;
  CustomPlacement?: string;
  Forest?: boolean;
  AntiquityPriority?: number;
  QuoteAudio?: string;
  Settlement?: boolean;
  FollowRulesInWB?: boolean;
}

interface FloatFeaturesAttributes {
  FeatureType?: string;
  Name?: string;
  Description?: string;
  Quote?: string;
  Coast?: boolean;
  NoCoast?: boolean;
  NoRiver?: boolean;
  NoAdjacentFeatures?: boolean;
  RequiresRiver?: boolean;
  MovementChange?: number;
  SightThroughModifier?: number;
  Impassable?: boolean;
  NaturalWonder?: boolean;
  RemoveTech?: string;
  Removable?: boolean;
  AddCivic?: string;
  DefenseModifier?: number;
  AddsFreshWater?: boolean;
  Appeal?: number;
  MinDistanceLand?: number;
  MaxDistanceLand?: number;
  NotNearFeature?: boolean;
  Lake?: boolean;
  Tiles?: number;
  Adjacent?: boolean;
  NoResource?: boolean;
  DoubleAdjacentTerrainYield?: boolean;
  NotCliff?: boolean;
  MinDistanceNW?: number;
  CustomPlacement?: string;
  Forest?: boolean;
  AntiquityPriority?: number;
  QuoteAudio?: string;
  Settlement?: boolean;
  FollowRulesInWB?: boolean;
}

export function createFeatures(attributes: FixFeaturesAttributes): void;
